### ISSUE TITLE
Control height in notification

### ISSUE THREAD

**Issue by sspaul1976** [nodinosaur/ha_tv_dashboard_wiki#10]
First, this is an amazing app!  First easy way I have found to stream a camera as a notification to the TV. 

Is there a way to control the height or set an aspect ratio?  I only see width, which just makes a square and elongates the video. Tried to add "height" but looks ignored. 

Thank you!

**Comment by nodinosaur** [comment]
Hi,

Thank you for your kind words.

Yes, it was an oversight of mine and got lost in the recent Nvidia related fixes, it will be fixed in the next release.

My "design" was to always show a still before the video would stream, and the quickest fix is to add the appropriate [placeholder graphic](https://github.com/nodinosaur/ha_tv_dashboard_wiki/wiki/Graphical-assets) to "force" the aspect ratio.


Or if your notification provides a still then use that, like [nest hello](https://github.com/nodinosaur/ha_tv_dashboard_wiki/wiki/Mobile-Push-notification-Detect-person), otherwise grab a snapshot - [see the example](https://github.com/nodinosaur/ha_tv_dashboard_wiki/wiki/Mobile-Push-notifcation-camera-snapshot-example-automation) 




Here is an example of a script to add the placeholder, you’ll notice the `image`

```yaml
alias: Stream Driveway Cam
description: ""
sequence:
  - action: notify.mobile_app_loungetv
    data:
      message: ""
      title: Driveway Cam
      data:
        notif_type: stream
        video: hls
        image: http://192.168.86.10:8123/local/tmp/ar_16x9_dark.jpg
        icon: http://192.168.86.10:8123/local/nest/nest_camera_150px.png
        filter: null
        entity_id: camera.driveway_cam
        camera_name: Driveway Cam
        config:
          fontsize: medium
          position: bottom-left
          duration: 120
          transparency: 5
          color: "#282C35"
icon: hass:cctv
```

Use the File Editor addon and in your `www` folder create a new folder called `tmp` and pop the images in there.

I hope this helps
