### ISSUE TITLE
live video RTSP, Webrtc challenges

### ISSUE THREAD

**Issue by Doug411** [nodinosaur/ha_tv_dashboard_wiki#11]
Cool app.  I have experimented a bit with notifications and I have a couple of questions.   I am currently using pipup to serve web-rtc live video popups from my cameras to my shield.  I tried using your mobile notify function, but was only able to get HLS to work when supplying the camera entity as the source.  In the documentation it seems to indicate that in the video field, you can supply a value of "HLS" or supply an RTSP link.  That is a bit confusing to me, because the camera entity is required (why put a URL in the video field for the source, and supply a camera entity?.  I tried various combinations of putting Webrtc links and RTSP links in the video field, while suplying the camera entity, blanking out the camera entity and eliminating the camera entity entirely from the service request.  Nothing I tried worked.  The only thing I was able to make work is putting HLS in the video field and supplying a camera entity.   I am popping up your mobile notification and the pipup web-rtc notification at the same time to experiment.   HLS lags by 7 seconds or so.   Movements in the pipup web-rtc notification are near real time.   Also the aspect ratio seems odd.  My pipup notification is 16:9, wheras the mobile notification almost looks 9:16 :)    Its tall, and seems a bit distorted comparitively.  I'd love to move over to your app for notifications (as pipup has been unsupported for years, and requires side loading).  However, the video lag with HLS is too much for my current use case.   Is there something I am doing wrong or not doing to make the RTSP feed work?  Do you have any plans to support http links (like web-rtc)?   Again, kudos.  Great start.  The dashboard stuff looks pretty slick (I may experiment with it when I get around to actually building a dashboard).  :)

**Comment by Doug411** [comment]
FYI, i'm running frigate.  The RTSP and Webrtc links I tried were from go2rtc.  They work in vlc and pipup respectively.

**Comment by nodinosaur** [comment]
Hi,

I'll answer in parts.

Thank you for your kind words.

Yes, the height was an oversight of mine and got lost in the recent Nvidia related fixes, it will be fixed in the next release.

My "design" was to always show a still before the video would stream, and the quickest fix is to add the appropriate [placeholder graphic](https://github.com/nodinosaur/ha_tv_dashboard_wiki/wiki/Graphical-assets) to "force" the aspect ratio.


Or if your notification provides a still then use that, like [nest hello](https://github.com/nodinosaur/ha_tv_dashboard_wiki/wiki/Mobile-Push-notification-Detect-person), otherwise grab a snapshot - [see the example](https://github.com/nodinosaur/ha_tv_dashboard_wiki/wiki/Mobile-Push-notifcation-camera-snapshot-example-automation) 


Here is an example of a script to add the placeholder, you’ll notice the `image`

```yaml
alias: Stream Driveway Cam
description: ""
sequence:
  - action: notify.mobile_app_loungetv
    data:
      message: ""
      title: Driveway Cam
      data:
        notif_type: stream
        video: hls
        image: http://192.168.86.10:8123/local/tmp/ar_16x9_dark.jpg
        icon: http://192.168.86.10:8123/local/nest/nest_camera_150px.png
        filter: null
        entity_id: camera.driveway_cam
        camera_name: Driveway Cam
        config:
          fontsize: medium
          position: bottom-left
          duration: 120
          transparency: 5
          color: "#282C35"
icon: hass:cctv
```

Use the File Editor addon and in your `www` folder create a new folder called `tmp` and pop the images in there.

I hope this helps
