### ISSUE TITLE
Feature request: Concurrent notifications

### ISSUE THREAD

**Issue by rekenaar00** [nodinosaur/ha_tv_dashboard_wiki#3]
Hi there!

Would it be possible to allow multiple concurrent notifications?

For example, my camera feed take ~5 seconds to load the first time after the TV was switched on. So I want to show the camera snapshot image at left_bottom while the camera feed loads at right_bottom.

I know I can put the image as icon of the video, but that is too small, so I would prefer to show it bigger while the feed is loading.

Another option if above is not posible,  is if the image is displayed while the video is loading.

Thanks

**Comment by nodinosaur** [comment]
If I understand correctly, then what you are asking for is already built in.

The `image` property is for this reason, your automation can grab a camera snapshot, and you add that into the data packet that is sent. The video starts playing on top of the image once it is ready.

Here is a sample HA Automation that achieves this

create a `Input Button` Helper called `Camera Snapshot Notification` and add a Tile card with `input_button.camera_snapshot_notification` as the entity. When you tap the card it will execute the automation below

```yaml
alias: Camera Snapshot notification
description: ""
triggers:
  - trigger: state
    entity_id:
      - input_button.camera_snapshot_notification
    to: null
conditions: []
actions:
  - variables:
      local_ip: http://{{ states("sensor.local_ip") }}:8123
      image: /config/www/tmp/front_cam_{{ now().strftime("%Y%m%d-%H%M%S") }}.jpg
      image_path: "{{local_ip}}{{ image | replace(\"config/www\", \"local\") }}"
  - action: camera.snapshot
    target:
      entity_id: camera.front_cam
    data:
      filename: "{{ image }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - action: notify.mobile_app_emulatortv
    metadata: {}
    data:
      message: UFO Detected
      title: Front Cam
      data:
        image: "{{ image_path }}"
        video: hls
        icon: "{{ local_ip }}/local/nest/nest_camera_150px.png"
        filter: doorbell
        entity_id: camera.front_door
        camera_name: Front Door
        config:
          fontsize: medium
          position: bottom-left
          duration: 5
          transparency: 5
          color: grey
          interrupt: 1
mode: single
```

if you have a Nest camera then the snapshot process is simpler as it is already available:
```yaml
variables:
  local_ip: http://{{ states('sensor.local_ip') }}:8123
  image: "{{ local_ip }}/api/nest/event_media/{{ trigger.event.data.device_id }}/{{ trigger.event.data.nest_event_id }}/thumbnail"
    # and you don't need image_path
```

see the [docs for more details](https://github.com/nodinosaur/ha_tv_dashboard_wiki/wiki/Mobile-Push-notification-config)

I hope this helps?
