### ISSUE TITLE
How to put a video into a notification

### ISSUE THREAD

**Issue by RN-Say** [nodinosaur/ha_tv_dashboard_wiki#8]
I am very excited about the potential of this project. I grabbed a google 4K streamer because none of my other devices had a compatible android version. I'm able to put up notifications with still images quite well, but I can't figure out how to get my Reolink Doorbell video to show up in a notification.

I use Frigate with the Reolink video doorbell and 5 camera feeds show up on the cameras page as: 
Doorbell2
Reolink Video Doorbell Wifi Clear
Reolink Video Doorbell Wifi Fluent
Reolink Video Doorbell Wifi Snapshots Clear
Reolink Video Doorbell Wifi Snapshots Fluent.

I have multiple associated camera entities in HA:
camera.doorbell2
camera.doorbell_main
camera.doorbell_sub
camera.doorbell_snapshots
camera.doorbell_snapshots_sub

Here is what I've tried in Developer Tools>Actions

```
action: notify.gstreamer
data:
  message: Front Door
  title: Person Detected
  data:
    video: rtsp://admin:password_redacted@192.168.11.16:554/h264Preview_01_main
   # video: hls
   # video:
   #    path: rtsp://admin:password_redacted@192.168.11.16:554/h264Preview_01_main
    icon: 
      path: /config/www/tmp/snapshot-doorbell.jpg
    entity_id: camera.doorbell2
    camera_name: Doorbell
    config:
      fontsize: medium
      position: bottom-right
      width: 240
      show_frame: true
      duration: 60
      transparency: 50
      color: red
```

Are you able to explain where I'm going wrong? Let me know if you need other info about my system. Thanks

**Comment by nodinosaur** [comment]
Hi Ron
Thank you for the kind words.

I wonder are you using the [mobile app integration](https://www.home-assistant.io/integrations/mobile_app/) or attempting to use [Notifications for Android TV / Fire TV](https://www.home-assistant.io/integrations/nfandroidtv) (NfATV)?

From the code example you pasted above It looks like you've used a configuration the latter - which is not required and I will be deprecating support for NfATV that are still using that platform. 
- I wonder did you create the above from following the Wiki directions? Maybe I might need to improve them a little so they are less confusing.

### As far as making the overlay popup work:
Can you try using adapting [this example](https://github.com/nodinosaur/ha_tv_dashboard_wiki/wiki/Mobile-Push-notifcation-camera-snapshot-example-automation) for your use case? (Obviously change the entity names and id's)

I have put some further examples on the Config page like [this one](https://github.com/nodinosaur/ha_tv_dashboard_wiki/wiki/Mobile-Push-notification-config#the-minimum-you-could-send-but-should-choose-an-image-or-video)

The popup overlay works well with the `HLS` feed (_which is the same feed as used on the cameras screen_). 

Let me know if you can get it working with the example code and the HLS feed.

Once that is working, I would ask you if the you could try RTSP feed for me? As unfortunately, I don't have a camera that supports the full protocol and cannot seem to be able to test properly.

Thanks

**Comment by RN-Say** [comment]
Yes, you were correct that I was trying to use NfATV. It worked easily when I switched to the mobile app integration. 

I tried rtsp and hls. Both worked, however, hls video almost always came up at 1-2 seconds. At worst, it equaled the rtsp which consistently took about 7 seconds.  

FWIW, I couldn't notice any difference between the 2 camera entities provided by the Reolink integration and the camera entity provided by the frigate integration. 

```
action: notify.mobile_app_living_room_tv
data: 
  message: UFO Detected
  title: Front Cam
  data:
    video: hls
    filter: doorbell
    entity_id: camera.doorbell2
    camera_name: Doorbell
    config:
      fontsize: medium
      position: bottom-right
      duration: 60
      transparency: 5
      color: grey
      interrupt: 1
```
